# Generated by Django 4.0.3 on 2022-03-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tags_alter_editor_options_editor_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
    ]
