# Generated by Django 3.2.7 on 2022-03-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsletterrecipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
